name: Deploy Bot

on:
  push:
    branches:
      - main  # O reemplaza con el nombre de tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Usa la versión 16 de Node.js

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Usa la versión 3.9 de Python

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bot
        run: python3.9 bot.py  # Cambia la versión si lo necesitas
