name: Reinicio Autom치tico

on:
  workflow_run:
    workflows: ["Reinicio automatico"]
    types:
      - completed

jobs:
  reiniciar:
    runs-on: ubuntu-latest

    steps:
      - name: Reiniciar flujo de trabajo
        run: |
          if [[ $GITHUB_EVENT_NAME == 'workflow_run' && $GITHUB_EVENT_PATH ]]; then
            completed_workflow_id=$(jq -r '.workflow_run.id' "$GITHUB_EVENT_PATH")
            workflow_name="Reinicio automatico"
            current_time=$(date +%s)
            workflow_start_time=$(date -d "$(jq -r '.workflow_run.created_at' "$GITHUB_EVENT_PATH")" +%s)
            max_execution_time=$((4 * 60 * 60))  # 4 horas en segundos

            if [[ "$((current_time - workflow_start_time))" -ge "$max_execution_time" ]]; then
              echo "El flujo de trabajo ha estado en ejecuci칩n durante 4 horas. Reiniciando..."
              curl -X POST \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/workflows/$workflow_name/dispatches" \
                -d '{"ref": "main"}'
            else
              echo "El flujo de trabajo ha estado en ejecuci칩n durante menos de 4 horas."
            fi
          else
            echo "Este paso solo se ejecuta en la finalizaci칩n del flujo de trabajo."
          fi
